## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values.

In [20]:
import numpy as np

array = np.random.rand(3,6)

print(array)

[[0.1273986  0.9629713  0.12483722 0.46315197 0.8676274  0.7370514 ]
 [0.54361206 0.38494616 0.01379543 0.71039924 0.83139245 0.8019369 ]
 [0.98378948 0.73485811 0.27905945 0.23148309 0.39742375 0.32047289]]


Check the dimension you have created is correct (use “*.shape*”)

In [10]:
array.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [21]:
array[2,5]

np.float64(0.3204728868714162)

In [22]:
array[1,4] = 19.75

print(array)

[[1.27398601e-01 9.62971299e-01 1.24837225e-01 4.63151968e-01
  8.67627403e-01 7.37051404e-01]
 [5.43612059e-01 3.84946163e-01 1.37954324e-02 7.10399243e-01
  1.97500000e+01 8.01936897e-01]
 [9.83789481e-01 7.34858108e-01 2.79059454e-01 2.31483085e-01
  3.97423750e-01 3.20472887e-01]]


Extract the 2nd and the 3rd row of the array you created.

In [25]:
array[1]

array([5.43612059e-01, 3.84946163e-01, 1.37954324e-02, 7.10399243e-01,
       1.97500000e+01, 8.01936897e-01])

In [26]:
array[2]

array([0.98378948, 0.73485811, 0.27905945, 0.23148309, 0.39742375,
       0.32047289])